apiVersion: v1
kind: Service
metadata:
  name: food-finder
  labels:
    app: food-finder
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: food-finder
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-finder-deployment
spec:
  selector:
    matchLabels:
      app: food-finder
  template:
    metadata:
      labels:
        app: food-finder
    spec:
      containers:
      - name: food-finder
        image: ${IMAGE_NAME}
        ports:
        - containerPort: 8080
        env:
        - name: PROJECT_ID
          value: ${PROJECT_ID}
