apiVersion: v1
kind: Service
metadata:
  name: food-item-lookup
  labels:
    app: food-item-lookup
spec:
  ports:
  - port: 50053
    protocol: TCP
  selector:
    app: food-item-lookup
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-item-lookup-deployment
spec:
  selector:
    matchLabels:
      app: food-item-lookup
  template:
    metadata:
      labels:
        app: food-item-lookup
    spec:
      containers:
      - name: food-item-lookup
        image: ${IMAGE_NAME}
        ports:
        - containerPort: 50053
        env:
        - name: PROJECT_ID
          value: ${PROJECT_ID}

