apiVersion: v1
kind: Service
metadata:
  name: food-supplier
  labels:
    app: food-supplier
spec:
  ports:
  - port: 50052
    protocol: TCP
  selector:
    app: food-supplier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-supplier-deployment
spec:
  selector:
    matchLabels:
      app: food-supplier
  template:
    metadata:
      labels:
        app: food-supplier
    spec:
      containers:
      - name: food-supplier
        image: ${IMAGE_NAME}
        ports:
        - containerPort: 50052
        env:
        - name: PROJECT_ID
          value: ${PROJECT_ID}
